# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-23 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='recast_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cast_time',
            field=models.FloatField(null=True),
        ),
    ]
