# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-24 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190122_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='phys_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
