# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_spell_phys_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='home.Spell')),
            ],
        ),
    ]
