# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='acquisition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
